In [5]:
import pandas as pd
import numpy as np

Reading the text file which has booking data

In [14]:
df= pd.read_csv('hotel_bookings.txt',delimiter='\t')
df.head()

         Date Company        Person Name  Room number
0  1-Jan-2022  Avamba  Anatole Ridehalgh       4008.0
1  1-Jan-2022    Fatz    Aldrich McKevin       2002.0
2  1-Jan-2022   Leexo    Stanley Hadrill       4012.0
3      Hotels     NaN                NaN          NaN
4  1-Jan-2022  Rhyzio       Lyndell Tice       1006.0

In [ ]:
 # Remove rows with missing values in 'Room number' column and set 'Text Value' to 'Date' where 'Room number' is NaN
df["Text Value"] = np.where(df["Room number"].isna(), df["Date"], np.nan)
df.head()

         Date Company        Person Name  Room number Text Value
0  1-Jan-2022  Avamba  Anatole Ridehalgh       4008.0        NaN
1  1-Jan-2022    Fatz    Aldrich McKevin       2002.0        NaN
2  1-Jan-2022   Leexo    Stanley Hadrill       4012.0        NaN
3      Hotels     NaN                NaN          NaN     Hotels
4  1-Jan-2022  Rhyzio       Lyndell Tice       1006.0        NaN

In [ ]:
df["Text Value"].fillna(method='bfill', inplace=True)
# Remove rows with any remaining NaN values
df.dropna(inplace=True)
df.tail()

/var/folders/c7/j3h2vwcs1x35b0szt8dxshb00000gn/T/ipykernel_73888/2842688513.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Text Value"].fillna(method='bfill', inplace=True)
/var/folders/c7/j3h2vwcs1x35b0szt8dxshb00000gn/T/ipykernel_73888/2842688513.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Text Value"].fillna(method='bfill', inplace=True)

           Date       Company        Person Name  Room number Text Value
186  1-Jan-2022        Tagpad     Stephani Lafee       1015.0    Expedia
187  1-Jan-2022        Meevee    Victoria Lavery       7002.0    Expedia
191  1-Jan-2022      Fivechat     Corabella Saye       4008.0     Hotels
192  1-Jan-2022       Innojam  Leandra Potapczuk       5002.0     Hotels
193  1-Jan-2022  Twitterworks    Valentia Ledson       1010.0     Hotels